name: export_files_generator
description: Dart export files generator.
version: 1.0.2
homepage: https://github.com/ScarabeiDart/
author: J Fixby <dart@jfixby.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  scarabei: ^1.4.6
  scarabei_reyer: ^1.4.6

dev_dependencies:
  test: ^0.12.0

dependency_overrides:
#    scarabei:
#      path: ../../ScarabeiDart/ScarabeiDart/scarabei
#    scarabei_reyer:
#      path: ../../ScarabeiDart/ScarabeiDart/scarabei_reyer


